openapi: 3.0.3
info:
  title: ReelBanana Align Captions API
  version: 1.0.0
servers:
  - url: https://reel-banana-align-captions-423229273041.us-central1.run.app
  - url: http://localhost:8081
components:
  securitySchemes:
    AppCheck:
      type: apiKey
      in: header
      name: X-Firebase-AppCheck
  schemas:
    Error:
      type: object
      required: [code, message]
      properties:
        code: { type: string }
        message: { type: string }
        details: { type: string }
        requestId: { type: string }
paths:
  /align:
    post:
      summary: Generate SRT captions from a GCS audio file
      security:
        - AppCheck: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [projectId, gsAudioPath]
              properties:
                projectId: { type: string }
                gsAudioPath: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  srtPath: { type: string }
                  requestId: { type: string }
        '400': { description: Invalid args, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '401': { description: App Check invalid, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '422': { description: No words detected, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '500': { description: Internal, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

