openapi: 3.0.3
info:
  title: ReelBanana Compose Music API
  description: |
    Service for generating AI-composed orchestral music based on narration scripts.
    Creates mood-appropriate background music for video production.
  version: 1.0.0
  contact:
    name: ReelBanana API Support
    url: https://reel-banana-35a54.web.app
servers:
  - url: https://reel-banana-compose-music-423229273041.us-central1.run.app
    description: Production server
  - url: http://localhost:8084
    description: Development server

security:
  - AppCheck: []

paths:
  /compose-music:
    post:
      summary: Generate AI-composed music
      description: |
        Analyzes the narration script to determine mood and generates
        appropriate orchestral background music using AI composition.
      operationId: composeMusic
      security:
        - AppCheck: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - projectId
                - narrationScript
              properties:
                projectId:
                  type: string
                  description: Unique project identifier
                  example: "proj_123456789"
                narrationScript:
                  type: string
                  description: Narration script for mood analysis
                  example: "Once upon a time, in a magical forest far away, there lived a brave little rabbit..."
            examples:
              music_composition:
                summary: Music composition
                value:
                  projectId: "proj_123456789"
                  narrationScript: "Once upon a time, in a magical forest far away, there lived a brave little rabbit who loved to explore. Every morning, he would hop through the tall grass and discover new wonders."
      responses:
        '200':
          description: Music composed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Music composed successfully."
                  gsMusicPath:
                    type: string
                    description: Google Cloud Storage path to the music file
                    example: "gs://oneminute-movie-in/proj_123456789/music.mp3"
                  mood:
                    type: string
                    description: Detected mood from the script
                    example: "adventurous"
                  duration:
                    type: number
                    description: Music duration in seconds
                    example: 45.2
              examples:
                success:
                  summary: Successful composition
                  value:
                    message: "Music composed successfully."
                    gsMusicPath: "gs://oneminute-movie-in/proj_123456789/music.mp3"
                    mood: "adventurous"
                    duration: 45.2
        '400':
          description: Bad request - missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missing_fields:
                  summary: Missing required fields
                  value:
                    error: "Missing required fields: projectId, narrationScript"
        '401':
          description: Unauthorized - App Check token required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                app_check_required:
                  summary: App Check token required
                  value:
                    error: "App Check token required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                composition_failed:
                  summary: Music composition failed
                  value:
                    error: "Failed to compose music"
                    details: "AI composition service error or network issue"

components:
  securitySchemes:
    AppCheck:
      type: apiKey
      in: header
      name: X-Firebase-AppCheck
      description: Firebase App Check token for request verification
  schemas:
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
        details:
          type: string
          description: Additional error details (optional)
      example:
        error: "An error occurred"
        details: "Additional context about the error"

tags:
  - name: Music
    description: AI music composition and generation
