openapi: 3.0.3
info:
  title: ReelBanana Narrate API
  version: 1.0.0
servers:
  - url: https://reel-banana-narrate-423229273041.us-central1.run.app
    description: Production
  - url: http://localhost:8080
    description: Local
components:
  securitySchemes:
    AppCheck:
      type: apiKey
      in: header
      name: X-Firebase-AppCheck
  schemas:
    Error:
      type: object
      required: [code, message]
      properties:
        code: { type: string }
        message: { type: string }
        details: { type: string }
        requestId: { type: string }
paths:
  /narrate:
    post:
      summary: Generate narration audio from text via ElevenLabs
      security:
        - AppCheck: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [projectId, narrationScript]
              properties:
                projectId: { type: string }
                narrationScript: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  gsAudioPath: { type: string }
        '400': { description: Invalid args, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '401': { description: App Check invalid, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '500': { description: Internal, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

