openapi: 3.0.3
info:
  title: ReelBanana Render API
  version: 1.0.0
servers:
  - url: https://reel-banana-render-423229273041.us-central1.run.app
  - url: http://localhost:8082
components:
  securitySchemes:
    AppCheck:
      type: apiKey
      in: header
      name: X-Firebase-AppCheck
  schemas:
    Error:
      type: object
      required: [code, message]
      properties:
        code: { type: string }
        message: { type: string }
        details: { type: string }
        requestId: { type: string }
    Scene:
      type: object
      properties:
        narration: { type: string }
        imageCount: { type: integer }
        camera: { type: string, enum: [zoom-in, zoom-out, pan-left, pan-right, static] }
        transition: { type: string, enum: [fade, wipeleft, wiperight, circleopen, dissolve, none] }
        duration: { type: number }
paths:
  /render:
    post:
      summary: Render final video (returns signed URL)
      security:
        - AppCheck: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [projectId, scenes, gsAudioPath, srtPath]
              properties:
                projectId: { type: string }
                scenes:
                  type: array
                  items:
                    $ref: '#/components/schemas/Scene'
                gsAudioPath: { type: string }
                srtPath: { type: string }
                gsMusicPath: { type: string, nullable: true }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  videoUrl: { type: string }
        '400': { description: Invalid args, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '401': { description: App Check invalid, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '500': { description: Internal or ffmpeg failure, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

