name: Deploy Cloud Run services

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/cloud-run-deploy.yml'

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud defaults
        run: |
          gcloud config set project "$PROJECT_ID"
          gcloud config set run/region "$REGION"
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            upload-assets:
              - 'backend/upload-assets/**'
            narrate:
              - 'backend/narrate/**'
            align-captions:
              - 'backend/align-captions/**'
            compose-music:
              - 'backend/compose-music/**'
            render:
              - 'backend/render/**'
            polish:
              - 'backend/polish/**'
            api-key-service:
              - 'backend/api-key-service/**'

      - name: Deploy upload-assets
        if: steps.changes.outputs.upload-assets == 'true'
        run: |
          ENV_FLAGS=""
          [[ -n "$INPUT_BUCKET_NAME" ]] && ENV_FLAGS+=" --set-env-vars=INPUT_BUCKET_NAME=$INPUT_BUCKET_NAME"
          gcloud run deploy reel-banana-upload-assets --source backend/upload-assets --allow-unauthenticated $ENV_FLAGS
        env:
          INPUT_BUCKET_NAME: ${{ secrets.INPUT_BUCKET_NAME }}

      - name: Deploy narrate
        if: steps.changes.outputs.narrate == 'true'
        run: |
          ENV_FLAGS=""
          [[ -n "$ELEVENLABS_API_KEY" ]] && ENV_FLAGS+=" --set-env-vars=ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY"
          [[ -n "$INPUT_BUCKET_NAME" ]] && ENV_FLAGS+=" --set-env-vars=INPUT_BUCKET_NAME=$INPUT_BUCKET_NAME"
          gcloud run deploy reel-banana-narrate --source backend/narrate --allow-unauthenticated $ENV_FLAGS
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          INPUT_BUCKET_NAME: ${{ secrets.INPUT_BUCKET_NAME }}

      - name: Deploy align-captions
        if: steps.changes.outputs.align-captions == 'true'
        run: |
          ENV_FLAGS=""
          [[ -n "$INPUT_BUCKET_NAME" ]] && ENV_FLAGS+=" --set-env-vars=INPUT_BUCKET_NAME=$INPUT_BUCKET_NAME"
          gcloud run deploy reel-banana-align-captions --source backend/align-captions --allow-unauthenticated $ENV_FLAGS
        env:
          INPUT_BUCKET_NAME: ${{ secrets.INPUT_BUCKET_NAME }}

      - name: Deploy compose-music
        if: steps.changes.outputs.compose-music == 'true'
        run: |
          ENV_FLAGS=""
          [[ -n "$GEMINI_API_KEY" ]] && ENV_FLAGS+=" --set-env-vars=GEMINI_API_KEY=$GEMINI_API_KEY"
          [[ -n "$INPUT_BUCKET_NAME" ]] && ENV_FLAGS+=" --set-env-vars=INPUT_BUCKET_NAME=$INPUT_BUCKET_NAME"
          ENV_FLAGS+=" --set-secrets=ELEVENLABS_MUSIC_API_KEY=ELEVENLABS_MUSIC_API_KEY:latest"
          gcloud run deploy reel-banana-compose-music --source backend/compose-music --allow-unauthenticated $ENV_FLAGS
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          INPUT_BUCKET_NAME: ${{ secrets.INPUT_BUCKET_NAME }}

      - name: Deploy render
        if: steps.changes.outputs.render == 'true'
        run: |
          ENV_FLAGS=""
          [[ -n "$INPUT_BUCKET_NAME" ]] && ENV_FLAGS+=" --set-env-vars=INPUT_BUCKET_NAME=$INPUT_BUCKET_NAME"
          [[ -n "$OUTPUT_BUCKET_NAME" ]] && ENV_FLAGS+=" --set-env-vars=OUTPUT_BUCKET_NAME=$OUTPUT_BUCKET_NAME"
          gcloud run deploy reel-banana-render --source backend/render --allow-unauthenticated $ENV_FLAGS
        env:
          INPUT_BUCKET_NAME: ${{ secrets.INPUT_BUCKET_NAME }}
          OUTPUT_BUCKET_NAME: ${{ secrets.OUTPUT_BUCKET_NAME }}

      - name: Deploy polish
        if: steps.changes.outputs.polish == 'true'
        run: |
          ENV_FLAGS=""
          [[ -n "$API_KEY_SERVICE_URL" ]] && ENV_FLAGS+=" --set-env-vars=API_KEY_SERVICE_URL=$API_KEY_SERVICE_URL"
          [[ -n "$FAL_API_KEY" ]] && ENV_FLAGS+=" --set-env-vars=FAL_API_KEY=$FAL_API_KEY"
          [[ -n "$FAL_KEY" ]] && ENV_FLAGS+=" --set-env-vars=FAL_KEY=$FAL_KEY"
          [[ -n "$FAL_MODEL_UPSCALE" ]] && ENV_FLAGS+=" --set-env-vars=FAL_MODEL_UPSCALE=$FAL_MODEL_UPSCALE"
          [[ -n "$FAL_MODEL_INTERP" ]] && ENV_FLAGS+=" --set-env-vars=FAL_MODEL_INTERP=$FAL_MODEL_INTERP"
          [[ -n "$FAL_UPSCALE_ENDPOINT" ]] && ENV_FLAGS+=" --set-env-vars=FAL_UPSCALE_ENDPOINT=$FAL_UPSCALE_ENDPOINT"
          [[ -n "$FAL_INTERP_ENDPOINT" ]] && ENV_FLAGS+=" --set-env-vars=FAL_INTERP_ENDPOINT=$FAL_INTERP_ENDPOINT"
          [[ -n "$OUTPUT_BUCKET_NAME" ]] && ENV_FLAGS+=" --set-env-vars=OUTPUT_BUCKET_NAME=$OUTPUT_BUCKET_NAME"
          gcloud run deploy reel-banana-polish --source backend/polish --allow-unauthenticated $ENV_FLAGS
        env:
          API_KEY_SERVICE_URL: ${{ secrets.API_KEY_SERVICE_URL }}
          FAL_API_KEY: ${{ secrets.FAL_API_KEY }}
          FAL_KEY: ${{ secrets.FAL_KEY }}
          FAL_MODEL_UPSCALE: ${{ secrets.FAL_MODEL_UPSCALE }}
          FAL_MODEL_INTERP: ${{ secrets.FAL_MODEL_INTERP }}
          FAL_UPSCALE_ENDPOINT: ${{ secrets.FAL_UPSCALE_ENDPOINT }}
          FAL_INTERP_ENDPOINT: ${{ secrets.FAL_INTERP_ENDPOINT }}
          OUTPUT_BUCKET_NAME: ${{ secrets.OUTPUT_BUCKET_NAME }}

      - name: Deploy api-key-service
        if: steps.changes.outputs.api-key-service == 'true'
        run: |
          # Enable CORS origins via env if needed, otherwise deploy with defaults
          ENV_FLAGS=""
          gcloud run deploy reel-banana-api-key-service --source backend/api-key-service --allow-unauthenticated $ENV_FLAGS

      - name: Deployment Summary
        run: |
          echo "🚀 Cloud Run Deployment Summary:"
          echo "================================"
          [[ "${{ steps.changes.outputs.upload-assets }}" == "true" ]] && echo "✅ upload-assets - DEPLOYED" || echo "⏭️  upload-assets - SKIPPED (no changes)"
          [[ "${{ steps.changes.outputs.narrate }}" == "true" ]] && echo "✅ narrate - DEPLOYED" || echo "⏭️  narrate - SKIPPED (no changes)"
          [[ "${{ steps.changes.outputs.align-captions }}" == "true" ]] && echo "✅ align-captions - DEPLOYED" || echo "⏭️  align-captions - SKIPPED (no changes)"
          [[ "${{ steps.changes.outputs.compose-music }}" == "true" ]] && echo "✅ compose-music - DEPLOYED" || echo "⏭️  compose-music - SKIPPED (no changes)"
          [[ "${{ steps.changes.outputs.render }}" == "true" ]] && echo "✅ render - DEPLOYED" || echo "⏭️  render - SKIPPED (no changes)"
          [[ "${{ steps.changes.outputs.polish }}" == "true" ]] && echo "✅ polish - DEPLOYED" || echo "⏭️  polish - SKIPPED (no changes)"
          [[ "${{ steps.changes.outputs.api-key-service }}" == "true" ]] && echo "✅ api-key-service - DEPLOYED" || echo "⏭️  api-key-service - SKIPPED (no changes)"
          echo "================================"

