name: Deploy Stripe Service

on:
  push:
    paths:
      - 'backend/stripe-service/**'
      - '.github/workflows/deploy-stripe-service.yml'
  pull_request:
    paths:
      - 'backend/stripe-service/**'
      - '.github/workflows/deploy-stripe-service.yml'

env:
  PROJECT_ID: reel-banana-35a54
  SERVICE_NAME: reel-banana-stripe-service
  REGION: us-central1
  PORT: 8087

jobs:
  test:
    name: Test Stripe Service
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/stripe-service/package-lock.json
        
    - name: Install dependencies
      run: |
        cd backend/stripe-service
        npm ci
        
    - name: Run linting
      run: |
        cd backend/stripe-service
        npm run lint || echo "Linting not configured, skipping..."
        
    - name: Run tests
      run: |
        cd backend/stripe-service
        npm test || echo "Tests not configured, skipping..."
        
    - name: Security audit
      run: |
        cd backend/stripe-service
        npm audit --audit-level=high || echo "Security audit completed with warnings"

  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Configure Docker
      run: gcloud auth configure-docker
      
    - name: Build and Deploy to Cloud Run
      run: |
        cd backend/stripe-service
        
        # Build and deploy the service
        gcloud run deploy $SERVICE_NAME \
          --source . \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port $PORT \
          --set-env-vars NODE_ENV=production \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10 \
          --min-instances 0 \
          --concurrency 100 \
          --timeout 300 \
          --quiet
          
    - name: Get service URL
      id: get-url
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
        echo "service-url=$SERVICE_URL" >> $GITHUB_OUTPUT
        echo "Service deployed at: $SERVICE_URL"
        
    - name: Health Check
      run: |
        SERVICE_URL="${{ steps.get-url.outputs.service-url }}"
        echo "Waiting for service to be ready..."
        sleep 30
        
        # Test health endpoint
        for i in {1..5}; do
          if curl -f -s "$SERVICE_URL/health" > /dev/null; then
            echo "✅ Health check passed"
            break
          else
            echo "⏳ Health check attempt $i failed, retrying in 10s..."
            sleep 10
          fi
        done
        
        # Test config endpoint (should require auth)
        if curl -f -s "$SERVICE_URL/config" > /dev/null; then
          echo "❌ Config endpoint should require authentication"
          exit 1
        else
          echo "✅ Config endpoint properly requires authentication"
        fi
        
    - name: Update API Config
      run: |
        # Update the API config with the new service URL if it changed
        SERVICE_URL="${{ steps.get-url.outputs.service-url }}"
        echo "Service URL: $SERVICE_URL"
        
        # Check if the URL in config matches
        CURRENT_URL=$(grep -o 'https://reel-banana-stripe-service-[^"]*' config/apiConfig.ts | head -1)
        if [ "$CURRENT_URL" != "$SERVICE_URL" ]; then
          echo "⚠️  Service URL changed from $CURRENT_URL to $SERVICE_URL"
          echo "Please update config/apiConfig.ts manually"
        else
          echo "✅ Service URL matches configuration"
        fi

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [test, build-and-deploy]
    if: always()
    
    steps:
    - name: Notify Success
      if: needs.build-and-deploy.result == 'success'
      run: |
        echo "🎉 Stripe service deployed successfully!"
        echo "Service URL: ${{ needs.build-and-deploy.outputs.service-url }}"
        
    - name: Notify Failure
      if: needs.build-and-deploy.result == 'failure'
      run: |
        echo "❌ Stripe service deployment failed!"
        echo "Check the logs for details."
        exit 1
