name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Functions
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REEL_BANANA_35A54 }}
          PROJECT_ID: reel-banana-35a54

