name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - 'functions/**'
      - '.github/workflows/firebase-functions-deploy.yml'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REEL_BANANA_35A54 }}

      - name: Deploy Functions
        run: firebase deploy --only functions --project reel-banana-35a54

